# base config
agent: 'MHGNN' # GAT, MHGNN, MPNN, DDQN, MHGNNKGE
use_rl_model: false # false: shortest-path only (no RL model)
seed: 42
logger: 'wandb' # options: 'wandb', 'tensorboard', 'swanlab'
project_name: "satNetEnv3"
wandb_user_name: "wmqbit"
log_dir: 'logs'
model_dir: 'models' # 前面不要加 / ./ 等

device: "cuda:0"

# environment parameters
n_order_adj: 4 # number of order for adjacency matrix
action_size: 4 # number of possible actions
input_dim: 10 # dimension of input each node features

# training parameters
train_TA_model: true # whether to train the teacher agent network
use_student_network: false # whether to use the student network for action selection

mode_load_dir: "SimResults/MPNN/best_model/20-57-38_Starlink_3s_GTs_[2]/"
outputPath: '/home/qwer/Desktop/RL_SNRouting/SimResults/ShortestPath/2026-03-25/16-47-17_Starlink_3s_GTs_[4]_avUserLoad28/'
CurrentGTnumber: 4
power: 2 # epsilon 衰减中的幂指数因子，默认 2
