
# base config
agent: 'MPNN' #
project_name: "sn_MPNN-newreward"

# environment parameters
n_order_adj: 3 # number of order for adjacency matrix

#gat parameters
hidden_feats: 16
num_layers: 2 # corresponding to modifying n_order_adj
mlp_hidden_feats: [32, 32, 8]

#gat learner parameters
learning_rate: 0.0005
lr_decay_steps: 3000000
# end_factor: 0.5
updateF: 30